### Variáveis
@baseUrl = http://localhost:5000
@contentType = application/json


### GET - Obter um livro específico
GET {{baseUrl}}/api/livros/1


### POST - Criar outro livro
POST {{baseUrl}}/api/livros
Content-Type: {{contentType}}

{
  "titulo": "Clean Code (Edição Atualizada)",
  "autor": "Robert C. Martin"
}

### PUT - Atualizar um livro
PUT {{baseUrl}}/api/livros/1
Content-Type: {{contentType}}

{
  "titulo": "Clean Code - Edição Atualizada",
  "autor": "Robert C. Martin"
}

### DELETE - Remover um livro
DELETE {{baseUrl}}/api/livros/3

###
### EMPRÉSTIMOS
###

### GET - Listar todos os empréstimos
GET {{baseUrl}}/api/emprestimos

### POST - Criar um novo empréstimo
POST {{baseUrl}}/api/emprestimos
Content-Type: {{contentType}}

{
  "livroId": 1,
  "nomeUsuario": "João Silva",
  "dataEmprestimo": "2026-04-26T10:30:00",
  "dataDevolucao": null
}


### PUT - Atualizar data de devolução
PUT {{baseUrl}}/api/emprestimos/1
Content-Type: {{contentType}}

{
  "dataDevolucao": "2026-05-26T14:00:00"
}

### DELETE - Remover um empréstimo
DELETE {{baseUrl}}/api/emprestimos/2

